server:
  port: 18081
spring:
  #连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taohua_island?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
dubbo:
  application:
    name: taohua-dubbo-service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1.2181
